name: movie_project
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  flutter_dotenv: ^5.2.1
  dio: ^5.8.0+1
  freezed_annotation: ^3.0.0
  json_annotation:
  logger: ^2.5.0
  dartz: ^0.10.1
  skeletonizer: ^2.0.1
  intl: ^0.20.2
  pretty_dio_logger: ^1.4.0
  equatable:
  shimmer: ^3.0.0
  flutter_secure_storage:
  flutter_launcher_icons: ^0.14.4
  connectivity_plus:  ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.4.15
  freezed: ^3.0.6
  json_serializable:

flutter:

  uses-material-design: true
  assets:
    - .env
